ALL_PERMISSIONS = [
    "project:create",
    "project:edit",
    "project:archive",
    "project:delete",
    "iteration:create",
    "iteration:edit",
    "iteration:start",
    "iteration:complete",
    "requirement:create",
    "requirement:edit",
    "requirement:delete",
    "requirement:submit_review_req",
    "requirement:submit_review_spec",
    "requirement:submit_review_tests",
    "requirement:review_req",
    "requirement:review_spec",
    "requirement:review_tests",
    "test_case:create",
    "test_case:edit",
    "test_case:delete",
    "task:create",
    "task:edit",
    "task:delete",
    "task:test",
    "task:complete",
    "member:invite",
    "member:remove",
    "member:assign_role",
    "spec_template:edit",
]


def is_valid_permission(permission: str) -> bool:
    return permission in ALL_PERMISSIONS
