"""add_task_gen_fields

Revision ID: e9b5f5b096be
Revises: 4a7b2c8d9e01
Create Date: 2026-05-28 19:28:21.057093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9b5f5b096be'
down_revision: Union[str, Sequence[str], None] = '4a7b2c8d9e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_type', sa.String(length=20), nullable=True))
    op.add_column('tasks', sa.Column('source_section', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('spec_reference', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'spec_reference')
    op.drop_column('tasks', 'source_section')
    op.drop_column('tasks', 'task_type')
    # ### end Alembic commands ###
